name: Docker Publish CI

on:
  push:
    branches: [ 'main' ]
    tags: [ 'v*.*.*' ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - image: kungbean/sls
            dockerfile: docker/sls.dockerfile
          - image: kungbean/srtla
            dockerfile: docker/srtla.dockerfile
          - image: kungbean/nginx-rtmp
            dockerfile: docker/nginx_rtmp.dockerfile
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ matrix.image }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
